title: Family friends of 16 Eucalyptus
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.This config file is meant for settings that affect your whole blog, values
which you are expected to set up once and rarely need to edit after that.
or technical reasons, this file is *NOT* reloaded automatically when you use
jekyll serve'. If you change this file, 
please restart the 
server process.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

description_footer: 本站记录我学习之旅的沿途风景！